# avoid too long resource names being truncated and conflicting
nameOverride: aesc
indexInit:
  enabled: true
reindexing:
  # A database is required for reindexing, but Helm does not wait for the job to complete during installation.
  enabled: true
  # Allows tests to pass, otherwise when reindexing job is run as hook, installation will fail.
  hookExecution: false
  repository:
    url: http://repository
  db:
    url: jdbc:postgresql://postgresql:5432/postgres
ats:
  transform_url: http://alfresco-transform-services-router
  sfs_url: http://alfresco-transform-services-sfs
contentMediaTypeCache:
  enabled: false
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "1"
    memory: "1Gi"
search:
  url: http://elasticsearch:9200
messageBroker:
  url: nio://activemq-broker:61616
  username: admin
  password: admin
