{{- if not .Values.ats.existingConfigMap.name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alfresco-connector-cic.ats.fullname" . }}
  labels:
    {{- include "alfresco-connector-cic.labels" . | nindent 4 }}
data:
  SFS_URL: {{ required "You need to provide the SFS URL using either ats.sfsUrl value or a configmap" .Values.ats.sfsUrl | quote }}
{{- end }}
