{{- if not .Values.messageBroker.existingConfigMap.name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alfresco-connector-cic.mq.fullname" . }}
  labels:
    {{- include "alfresco-connector-cic.labels" . | nindent 4 }}
data:
  {{ template "alfresco-common.activemq.cm" (include "alfresco-connector-cic.activemq.url" .) }}
{{- end -}}
