{{- if not .Values.cic.existingConfigMap.name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "alfresco-connector-cic.fullname" . }}
  labels:
    {{- include "alfresco-connector-cic.labels" . | nindent 4 }}
data:
  HX_AUTH_TOKEN_URL: {{ .Values.cic.hxAuthTokenUrl | default "" | quote }}
  HX_INSIGHT_INGESTION_URL: {{ .Values.cic.hxInsightIngestionUrl | default "" | quote }}
{{- end -}}
