{{- if and .Values.bulkIngester.enabled (not .Values.db.existingConfigMap.name) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alfresco-connector-cic.database.fullname" . }}
  labels:
    {{- include "alfresco-connector-cic.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ required "Specifying DB URL is mandatory when not using existingConfigMap" .Values.db.url | quote }}
{{- end }}
