{{- if not .Values.messageBroker.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alfresco-connector-cic.mq.fullname" . }}
  labels:
    {{- include "alfresco-connector-cic.labels" . | nindent 4 }}
type: Opaque
data:
  BROKER_USERNAME: {{ required "messageBroker.username is required" .Values.messageBroker.username | b64enc | quote }}
  BROKER_PASSWORD: {{ required "messageBroker.password is required" .Values.messageBroker.password | b64enc | quote }}
{{- end }}
