{{- if and .Values.bulkIngester.enabled (not .Values.db.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alfresco-connector-cic.database.fullname" . }}
  labels:
    {{- include "alfresco-connector-cic.labels" $ | nindent 4 }}
type: Opaque
data:
  DATABASE_USERNAME: {{ required "db.username is required" .Values.db.username | b64enc | quote }}
  DATABASE_PASSWORD: {{ required "db.password is required" .Values.db.password | b64enc | quote }}
{{- end }}
