{{- if not .Values.repository.existingConfigMap.name }}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- $ctx := dict "Values" (dict "nameOverride" (printf "%s-%s" (.Values.nameOverride | default .Chart.Name) "repository")) "Chart" .Chart "Release" .Release }}
  name: {{ template "alfresco-search-community.fullname" $ctx }}
  labels:
    {{- include "alfresco-search-community.labels" . | nindent 4 }}
data:
  {{ .Values.repository.existingConfigMap.keys.url }}: {{ required ".repository.url is mandatory when not using existingConfigMap" .Values.repository.url }}
{{- end }}
