{{- if not .Values.transform.sharedSecret.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  {{- $ctx := dict "Values" (dict "nameOverride" (printf "%s-%s" (.Values.nameOverride | default .Chart.Name) "shared-secret")) "Chart" .Chart "Release" .Release }}
  name: {{ template "alfresco-search-community.fullname" $ctx }}
  labels:
    {{- include "alfresco-search-community.labels" $ | nindent 4 }}
type: Opaque
data:
  {{ .Values.transform.sharedSecret.existingSecret.keys.sharedSecret }}: {{ required ".transform.sharedSecret.value is mandatory when not using existingSecret" .Values.transform.sharedSecret.value | b64enc | quote }}
{{- end }}
