{{- if not .Values.db.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  {{- $ctx := dict "Values" (dict "nameOverride" (printf "%s-%s" (.Values.nameOverride | default .Chart.Name) "database")) "Chart" .Chart "Release" .Release }}
  name: {{ template "alfresco-search-community.fullname" $ctx }}
  labels:
    {{- include "alfresco-search-community.labels" $ | nindent 4 }}
type: Opaque
data:
  {{ .Values.db.existingSecret.keys.username }}: {{ .Values.db.username | default "" | b64enc | quote }}
  {{ .Values.db.existingSecret.keys.password }}: {{ .Values.db.password | default "" | b64enc | quote }}
{{- end }}
