apiVersion: v2
name: alfresco-connector-msteams
description: A Helm chart for deploying Alfresco connector msteams service
type: application
version: 2.8.0
appVersion: 2.1.3
dependencies:
  - name: alfresco-common
    version: 5.1.0
    repository: https://alfresco.github.io/alfresco-helm-charts/
