name: kics

on:
  pull_request:
    branches: [main]
    paths:
      - 'charts/**'
      - '.github/workflows/kics.yml'
  push:
    branches: [main]
    paths:
      - 'charts/**'
      - '.github/workflows/kics.yml'

permissions:
  security-events: write

jobs:
  kics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Run KICS Scan
        uses: checkmarx/kics-github-action@cd1f3774406f7818e3f79b77b093fe2ebaaf5c1d # v2.1.12
        with:
          path: 'charts'
          ignore_on_exit: results
          output_path: report-dir/
          output_formats: 'sarif'
          token: ${{ secrets.GITHUB_TOKEN }}
          enable_jobs_summary: true
          platform_type: 'kubernetes'
          disable_secrets: true
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@76621b61decf072c1cee8dd1ce2d2a82d33c17ed # v3.29.8
        with:
          sarif_file: report-dir/results.sarif
