---
name: Bump versions
run-name: >-
  Bump ${{ inputs.update-type || 'charts' }}${{ github.event_name == 'release' && format(' (triggered by {0})', github.event.release.tag_name) || '' }}

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      update-type:
        description: 'Which dependencies to bump'
        type: choice
        options:
        - charts
        - values
      alfresco-updatecli-ref:
        description: "The version to use for alfresco/alfresco-updatecli configs (used only when `values` is selected)"
        type: string
        default: master

jobs:
  bump-charts-dependencies:
    runs-on: ubuntu-latest
    name: Helm charts dependencies
    if: github.event_name == 'release' || inputs.update-type == 'charts'
    concurrency:
      group: ${{ github.workflow }}-charts
      cancel-in-progress: false
    env:
      IS_MAIN_BUMP: ${{ github.event_name == 'release' || github.ref_name == 'main' }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          ref: ${{ env.IS_MAIN_BUMP == 'true' && 'main' || github.ref }}

      - uses: >-
          Alfresco/alfresco-build-tools/.github/actions/get-branch-name@v18.19.0

      - name: Login to quay.io
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Install Updatecli
        uses: Alfresco/alfresco-build-tools/.github/actions/setup-updatecli@v18.19.0

      - run: updatecli apply
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-helm-docs@v18.19.0
      - name: Regenerate helm docs if necessary
        uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v18.19.0
        with:
          pre-commit-args: helm-docs || true
          skip_checkout: "true"

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: |
            🛠 Updatecli pipeline bump
          commit_user_name: ${{ vars.BOT_GITHUB_USERNAME }}
          commit_user_email: ${{ vars.BOT_GITHUB_EMAIL }}
          branch: ${{ env.IS_MAIN_BUMP == 'true' && 'updatecli-bump-helm' || github.ref_name }}
          create_branch: ${{ env.IS_MAIN_BUMP }}
          push_options: ${{ env.IS_MAIN_BUMP == 'true' && '--force' || '' }}

  bump-values-dependencies:
    runs-on: ubuntu-latest
    name: Image tags values dependencies
    if: inputs.update-type == 'values'
    concurrency:
      group: ${{ github.workflow }}-values
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - uses: >-
          Alfresco/alfresco-build-tools/.github/actions/get-branch-name@v18.19.0

      - name: Login to quay.io
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Install Updatecli
        uses: Alfresco/alfresco-build-tools/.github/actions/setup-updatecli@v18.19.0

      - name: Checkout updatecli configs
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: alfresco/alfresco-updatecli
          ref: ${{ inputs.alfresco-updatecli-ref || 'master' }}
          path: alfresco-updatecli

      - name: updatecli apply
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        run: |
          updatecli apply -c alfresco-updatecli/deployments/uber-manifest.tpl \
            -v alfresco-updatecli/deployments/values/supported-matrix.yaml \
            -v .github/updatecli-matrix-targets.yaml

      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-helm-docs@v18.19.0
      - name: Regenerate helm docs if necessary
        uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v18.19.0
        with:
          pre-commit-args: helm-docs || true
          skip_checkout: "true"

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: |
            🛠 Updatecli pipeline acs bump
          commit_user_name: ${{ vars.BOT_GITHUB_USERNAME }}
          commit_user_email: ${{ vars.BOT_GITHUB_EMAIL }}
          branch: ${{ github.ref_name == 'main' && 'updatecli-bump-acs' || github.ref_name }}
          create_branch: ${{ github.ref_name == 'main' && 'true' || 'false' }}
          push_options: ${{ github.ref_name == 'main' && '--force' || '' }}
